### ISSUE TITLE
rocococa-runtime dependency

### ISSUE THREAD

**Issue by shannah** [shannah/Java-Objective-C-Bridge#15]
The pom file includes a dependency for rococoa-runtime.  What is that for?   How heavy is it?  And could it be reasonably eliminated without crippling the lib?

@mojo2012

**Comment by mojo2012** [comment]
I added it while I experimented with NSRect-like structs.
I think we can easily elliminate it, I‘ll check it out later today

**Comment by mojo2012** [comment]
I removed the dependency!
