### ISSUE TITLE
Avoiding Notarization

### ISSUE THREAD

**Issue by Flameborn** [shannah/Java-Objective-C-Bridge#21]
Just a little background, I am currently working on a mod for a game, which requires cross-platform speech.

Is there a way to access Objective C classes, the *NSSpeechSynthesizer* class in particular, without an objective C bridge, i.e. directly?

Perhaps this is a bit out of scope for the project, however, I would like to avoid notarization, if possible, since it would unnecessarily complicate an open source project.

Any help is greatly appreciated.

**Comment by shannah** [comment]
I'm not sure I understand.  You want to access an Objective-C class from Java without a bridge?  I'm not sure how that would work.  How does this relate to notarization?

**Comment by mojo2012** [comment]
You could probably implement it in C and use JNA/JNI to interact with the C lib.
Are you planning on putting your app on the app store? Because than you will have to do the notarization anyway.

**Comment by Flameborn** [comment]
Sorry about the confusion.

As far as I understand, *Java-Objective-C* uses a *dylib* behind the scenes, which needs notarization under Catalina and above, which I’d like to avoid. I’m not sure whether there is a way to do this directly, i.e. via pure Java code, or via other means that do not require an additional binary, hence my question.

**Comment by Flameborn** [comment]
No, this is going to be an open-source project that provides modifications for a game. It’s likely going to be published via the Steam Workshop. Having an additional binary means that I would not be able to publish untrusted code (eventually) without notarization. It would also make it a bit more tedious to build for non-Mac users.

**Comment by shannah** [comment]
Does the steam workshop provide the JVM?  (I'm not familiar with Steam workshop).  If you are bundling your own JVM, which is the recommended way, then you'll need to notarize the JVM anyways.

**Comment by Flameborn** [comment]
The game has its own JRE included, which is notarized, so all the dylibs can be loaded. The mod is published as a jar file, which the game loads. If I include *Java-Objective-C*, at the moment it would need its library to be notarized.

**Comment by shannah** [comment]
You can include the libjcocoa.dylib inside your Game's app bundle.  Put it in the Contents/MacOS directory of the app bundle.  Then all of your mods will be able to use the bridge.

**Comment by Flameborn** [comment]
This is a great tip, thank you!

Unfortunately, I would still need to notarize the dylib.

**Comment by shannah** [comment]
You need to notarize the app anyway, the dylib would be notarized as a part of that process.

**Comment by Flameborn** [comment]
You are right. Unfortunately, as a mod creator, I am not the developer of the game, so I would need a separate developer license to do so. Sadly, open source is really not the way on Apple platforms, it seems.

My initial assumptions about requiring an external library were confirmed. Thank you very much for taking the time to help!
