### ISSUE TITLE
Are NativeLibLoader and Constants still used?

### ISSUE THREAD

**Issue by Marcono1234** [shannah/Java-Objective-C-Bridge#33]
It appears the classes `NativeLibLoader` and `Constants` are not used within this project?
Can they be removed?

Otherwise it might be worth rewriting `NativeLibLoader` using the functionality provided by the [`java.nio.file`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/nio/file/package-summary.html) package.

**Comment by shannah** [comment]
It doesn't look like it.  The library has gone through a few iterations for the native lib loading to satisfy various constraints.   NativeLibLoader is likely part of one of those previous iterations.
