### ISSUE TITLE
Requesting a new minor release for M1 Mac support

### ISSUE THREAD

**Issue by mezz** [shannah/Java-Objective-C-Bridge#43]
Hello,

Since support for Apple Silicon (https://github.com/shannah/Java-Objective-C-Bridge/commit/9c31f351bdd04c2270022e5a2e81f755a1608609) has been merged, could you release a 1.1.0 version of this library so that we can depend on it?

Thank you!

**Comment by shannah** [comment]
Done.  https://github.com/shannah/Java-Objective-C-Bridge/releases/tag/1.1

**Comment by mezz** [comment]
Thank you!
